#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.txt from the ACTUAL dependency graph.
#
# wede redistributes third-party code four ways: Go modules compiled into the
# backend binary, the large npm graph bundled into the embedded React IDE
# (CodeMirror, xterm, yjs, React, Tailwind, ...), the Inter / JetBrains Mono /
# Space Grotesk webfonts emitted as .woff2 into dist (OFL-1.1), and the
# mermaid/marked bundles vendored into the marketing site. MIT, BSD, ISC,
# Apache-2.0, MPL-2.0 and OFL-1.1 all require the copyright notice and licence
# text to accompany every copy.
#
#     ./scripts/gen-notices.sh
#
# THIRD-PARTY-NOTICES.txt is committed at the repo root; the build copies it to
# site/licenses.txt (embedded and served). It is NOT hand-maintained.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="THIRD-PARTY-NOTICES.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --- Go modules. wede's module graph includes MPL-2.0 code (hashicorp/yamux, via
# the embedded vulos-relay agent); MPL-2.0 is redistributable with notice, so the
# rules file allows it (and still denies GPL/AGPL/LGPL/SSPL/BUSL). The detector
# reproduces each module's licence text from the module cache.
DETECTOR="$(command -v go-licence-detector || true)"
if [[ -z "$DETECTOR" ]]; then
  echo "==> installing go.elastic.co/go-licence-detector@v0.10.0"
  GOBIN="$TMP/bin" go install go.elastic.co/go-licence-detector@v0.10.0
  DETECTOR="$TMP/bin/go-licence-detector"
fi

echo "==> resolving Go module graph"
go mod download
go list -m -json all | "$DETECTOR" \
  -includeIndirect \
  -rules scripts/notices/go-licence-rules.json \
  -noticeTemplate scripts/notices/go-modules.tmpl \
  -noticeOut "$TMP/go-notices.txt"

# --- npm packages actually bundled into dist (production deps only).
echo "==> resolving npm dependency graph"
[[ -d node_modules ]] || npm ci
npx --yes license-checker-rseidelsohn \
  --production --json --excludePrivatePackages --start . \
  | node scripts/notices/npm-notices.mjs > "$TMP/npm-notices.txt"

echo "==> composing $OUT"
{
  cat <<'HEADER'
================================================================================
wede — THIRD-PARTY NOTICES
================================================================================

This file is generated by scripts/gen-notices.sh from the actual dependency
graph. Do not edit it by hand.

wede is distributed under the MIT licence (see LICENSE). It bundles the
third-party software listed below. Each entry gives the component name, its
version, the licence it is distributed under, and the full text of that licence,
as those licences require. A running wede serves this file at /licenses.txt.

HEADER

  echo "================================================================================"
  echo "npm packages (bundled into the wede IDE frontend)"
  echo "================================================================================"
  echo
  echo "The Inter, JetBrains Mono and Space Grotesk webfonts below are shipped as"
  echo ".woff2 files in dist/assets/. SIL Open Font License 1.1 requires this notice"
  echo "and licence to accompany every redistribution of those font files."
  echo
  cat "$TMP/npm-notices.txt"

  echo "================================================================================"
  echo "Vendored browser assets (marketing site, site/assets/vendor/)"
  echo "================================================================================"
  echo
  for lic in site/assets/vendor/*.LICENSE; do
    [[ -e "$lic" ]] || continue
    echo "--------------------------------------------------------------------------------"
    cat "$lic"
    echo
  done

  echo "================================================================================"
  echo "Go standard library (compiled into the wede binary)"
  echo "================================================================================"
  echo
  echo "--------------------------------------------------------------------------------"
  echo "Component : The Go Programming Language standard library"
  echo "Version   : $(go env GOVERSION)"
  echo "Licence   : BSD-3-Clause (plus the Go patent grant, reproduced below)"
  echo "--------------------------------------------------------------------------------"
  echo
  cat "$(go env GOROOT)/LICENSE"
  echo
  cat "$(go env GOROOT)/PATENTS"
  echo

  echo "================================================================================"
  echo "Go modules (compiled into the wede binary)"
  echo "================================================================================"
  echo
  cat "$TMP/go-notices.txt"
} > "$OUT"

# Surface it. site/ is embedded into the binary and served at /site/*; the
# backend also serves this file at the public /licenses.txt route.
cp "$OUT" site/licenses.txt

echo "==> wrote $OUT and site/licenses.txt ($(wc -l < "$OUT" | tr -d ' ') lines)"
